name: Validate Submodule Commits

on:
  pull_request:
    branches:
      - master

jobs:
  submodule-commit-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Get Submodule Commit Hashes
        id: get-submodule-hashes
        run: |
          # 
          SDK_HASH=$(git submodule status submodules/sdk | awk '{print $1}')
          echo "SDK_hash=${SDK_HASH}" >> $GITHUB_OUTPUT

          MOTOKO_HASH=$(git submodule status submodules/motoko | awk '{print $1}')
          echo "MOTOKO_hash=${MOTOKO_HASH}" >> $GITHUB_OUTPUT

      - name: Validate Submodule 1 Commit
        env:
          SUBMODULE1_HASH: ${{ steps.get-submodule-hashes.outputs.submodule1_hash }}
        run: |
          # Latest SDK release commit
          LATEST_SDK=( "2013389f0d9aba148ab266647f0eb653d4514f1c" )

          # Check if the current SDK commit is latest release
          COMMIT1_FOUND=false
          for SDK_COMMIT in "${LATEST_SDK[@]}"; do
            if [[ "$SUBMODULE1_HASH" == "$LATEST_SDK"* ]]; then
              COMMIT1_FOUND=true
              break
            fi
          done

          # Fail the workflow if commit is not latest release
          if [[ "$COMMIT1_FOUND" == false ]]; then
            echo "Error: SDK commit $SDK_HASH is not latest release"
            exit 1
          fi

      - name: Validate Motoko Commit
        env:
          SUBMODULE2_HASH: ${{ steps.get-submodule-hashes.outputs.submodule2_hash }}
        run: |
          # Allowed commits for Motoko
          LATEST_MOTOKO=( "51fa74671829c59912c37500773cfaba950b0a1b" )

          # Check if the current Motoko commit is latest release
          COMMIT2_FOUND=false
          for MOTOKO_COMMIT in "${LATEST_MOTOKO[@]}"; do
            if [[ "$SUBMODULE2_HASH" == "$LATEST_MOTOKO"* ]]; then
              COMMIT2_FOUND=true
              break
            fi
          done

          # Fail the workflow if commit is not in allowed list
          if [[ "$COMMIT2_FOUND" == false ]]; then
            echo "Error: Motoko commit $SUBMODULE2_HASH is not latest release"
            exit 1
          fi
