name: Validate Submodule Commits
on:
  pull_request:
    branches:
      - master

jobs:
  submodule-commit-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Validate Submodule Commits
        run: |
          # Define latest release commits
          LATEST_SDK="0a82e042adec6f24ba53665312713923bf276a34"
          LATEST_MOTOKO="51fa74671829c59912c37500773cfaba950b0a1b"

          # Get current submodule commits
          SDK_HASH=$(git submodule status submodules/sdk | awk '{print $1}')
          MOTOKO_HASH=$(git submodule status submodules/motoko | awk '{print $1}')

          # Validate SDK commit
          if [[ "$SDK_HASH" != "$LATEST_SDK"* ]]; then
            echo "Error: SDK submodule is not on the latest release commit"
            exit 1
          fi

          # Validate Motoko commit
          if [[ "$MOTOKO_HASH" != "$LATEST_MOTOKO"* ]]; then
            echo "Error: Motoko submodule is not on the latest release commit"
            exit 1
          fi

          echo "All submodules are on their latest release commits"
